sonar.projectKey=SparkFlow-TQS_frontend
sonar.organization=sparkflow-tqs
sonar.projectVersion=0.1.0

# Source code location
sonar.sources=ui/app,ui/components,ui/lib,ui/types
sonar.tests=ui/tests
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/*.d.ts,**/test-results/**,**/playwright-report/**
sonar.test.exclusions=**/node_modules/**,**/build/**,**/dist/**

# Language specific settings
sonar.typescript.tsconfigPath=ui/tsconfig.json
sonar.javascript.lcov.reportPaths=ui/coverage/lcov.info

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Quality Gate
sonar.qualitygate.wait=true 