sonar.projectKey=SparkFlow-TQS_frontend
sonar.organization=sparkflow-tqs


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=sparkflow-frontend
sonar.projectVersion=0.1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=ui
sonar.exclusions=ui/node_modules/**,ui/.next/**,ui/out/**,ui/build/**,ui/dist/**,ui/package-lock.json

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# TypeScript specific settings
sonar.typescript.lcov.reportPaths=ui/coverage/lcov.info
sonar.javascript.lcov.reportPaths=ui/coverage/lcov.info

# Test coverage settings
sonar.coverage.exclusions=ui/**/*.test.ts,ui/**/*.test.tsx,ui/**/*.spec.ts,ui/**/*.spec.tsx